
version: '3.8'
services:
  app:
    image: janjanhada/project-server:1.5
    environment:
      SPRING_PROFILES_ACTIVE: prod,secret
    depends_on:
      - mysqlsudo
      - redis
    networks:
      - backend-net
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12341234
      MYSQL_DATABASE: 12341234
    ports:
      - "3306:3306"
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    networks:
      - backend-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  backend-net:
