spring:
  data:
    redis:
      host: redis_1
      password: ${custom.redis.password}
      port: 6379
  datasource:
    url: jdbc:mysql://mysql_1:3306/team07_prod?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: lldjlocal
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
