spring:
  datasource:
    url: jdbc:mysql://mysql:3306/12341234?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

    username: root
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379


